Repository Open-Science-Community-Saudi-Arabia/OSCSA_Website, pull requests merged in 2022-10, with the labels that each got.

#26 fix typo error
  index.html
Labels: outreachy, typo

#56 fix broken social links icons on footer
  index.html
Labels: outreachy, broken link

#111 Update outreachy.md
  .github/ISSUE_TEMPLATE/outreachy.md
Labels: enhancement, ready for review

#133 Updated the correct link to the website in the README.md file
  README.md
Labels: outreachy, broken link

#150 Update pull_project.yml
  .github/workflows/pull_project.yml
Labels: CI, Automation

#148 Feature: handle quick contact form with formspree.io - index.html, ar…
  ar-index.html
  index.html
Labels: bug, outreachy

#145 #Spelling and Grammatical errors on the OSCSA main site #144
  index.html
Labels: outreachy

#143 Analyzed & Increased Website SEO & Performance
  ar-index.html
  assets/css/style.css
  assets/img/css/bg1.jpeg
  assets/img/css/bg1.webp
  assets/img/landing/bg-01-01.png
  assets/img/landing/bg-01-01.webp
  assets/img/landing/logo1.png
  assets/img/landing/logo1.webp
  assets/img/landing/os.png
  assets/img/landing/os.webp
  assets/img/portfolio/UNISCO.jpeg
  assets/img/portfolio/UNISCO.webp
  assets/img/services-bg.jpeg
  assets/img/services-bg.webp
  index.html
Labels: enhancement

#201 fixed the contact form response display
  assets/vendor/php-email-form/validate.js
Labels: bug

#176 improved the web accesibility on the forms
  index.html
Labels: Accessibility

#154 Fixed broken/incorrect link on the landing page
  index.html
Labels: bug

#141 Fixed punctuation error on the landing page (footer section)
  index.html
Labels: typo

#165 Fixed Broken/dead link in Arabic file.
  ar-index.html
Labels: bug

#185 Fixed missing hamburger menu
  ar-index.html
Labels: bug

#187 [18/10/2022]Task3.2: Added event cards
  ar-index.html
  assets/css/style.css
  assets/img/event/event1.PNG
  assets/img/event/event2.PNG
  assets/img/event/event3.PNG
  index.html
Labels: enhancement

#218 Index - #215
  index.html
Labels: typo
